spring:
  application:
    name: ecommerce
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sqldb-smarttransfer-dev;MODE=MSSQLServer
    initialization-mode: always
    username:
    password:

---

spring:
  config:
    activate:
      on-profile: local
security:
  policy:
    password:
      complexity:
        min-length: 4

---

spring:
  config:
    activate:
      on-profile: test
security:
  policy:
    password:
      complexity:
        min-length: 8

---

spring:
  config:
    activate:
      on-profile: prod
security:
  policy:
    password:
      complexity:
        min-length: 8