spring:
  application:
    name: ecommerce
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sqldb-smarttransfer-dev;MODE=MSSQLServer
    initialization-mode: always
    username:
    password: